import './globals.css'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader';

export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GraveFinder',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  )
}
