import { Suspense } from "react";
import GravesList from "./GravesList";
import Loading from "../../(dashboard)/loading";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "GraveFinder | Graves",
  description: "Generated by create next app",
};

export default async function Graves() {
  const supabase = createServerComponentClient({ cookies });
  const { data } = await supabase.auth.getSession();

  if (!data.session) {
    redirect("/login");
  }

  return (
    <main>
      <nav>
        <div>
          <h2>Your Contributed Graves</h2>
          <p>
            <small>Available graves to locate.</small>
          </p>
        </div>
      </nav>

      <Suspense fallback={<Loading />}>
        <GravesList />
      </Suspense>
    </main>
  );
}
