export const metadata = {
  title: "GraveFinder | Activity",
  description: "Generated by create next app",
};

export default function CreateGrave() {
  return (
    <main>
      <h2 className="text-primary text-center">Activity</h2>
    </main>
  );
}
