import CreateForm from "./create/CreateForm";

export const metadata = {
  title: "GraveFinder | Add a new Grave",
  description: "Generated by create next app",
};

export default function CreateGrave() {
  return (
    <main>
      <h2 className="text-primary text-center">Add a new Grave</h2>
      <CreateForm />
    </main>
  );
}
