import Form from "./components/Form";
import { addGrave } from "./actions";

export const metadata = {
  title: "GraveFinder | Add a new Grave",
  description: "Generated by create next app",
};

export default async function CreateGrave() {
  return (
    <main>
      <h1 className="text-xl font-bold text-center mt-5">Add a new Grave</h1>
      <Form
        action={addGrave}
      />
    </main>
  );
}
